# Knative "production" Site Configuration (adds to or overrides "_default")

# Usage notes:
# To build with these settings, you run: "hugo --config production"
# Hugo build then uses every setting defined in "config/_default" and then merge
# all settings defined here for "staging" on top of all those define for "_default".

baseURL = "https://knative.dev/"
enableRobotsTXT = true

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-148338258-1"
